### PR TITLE
Add out of support within days config

### PR DESCRIPTION
**Pull request by IEvangelist**
Added a config value that will allow us to specify the number of additional days to consider flagging versions that will be out of support. For example:

```json
{
  "outOfSupportWithinDays": 90,
  "ignore": [
    "**/pinned-versions/**",
    "**/*.fsproj"
  ]
}
```

This will flag all out of support versions, but also versions that will be out of support 90 days from now.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @IEvangelist 

You can :shipit: when ready.

**Comment by Gakk** [comment]
@IEvangelist This flag is not documented in neither [README.md](https://github.com/dotnet/versionsweeper/blob/main/README.md) nor [action.yml](https://github.com/dotnet/versionsweeper/blob/main/action.yml). Is it still working, or has it been removed later?

**Comment by IEvangelist** [comment]
Good catch, @Gakk. Thanks for calling attention to this. Are you using this GitHub Action?

**Comment by Gakk** [comment]
I am product manager for a double digit number of products, and have for a long time used Dependabot to help manage both package upgrades and newer versions of actions.

A short while ago I looked at a .NET repository and noticed it used your action to check target version for projects.

When using a new product/package I usually read through release notes, issues and pull request to get a feeling on how the product is evolving and being maintained. That's when I noticed this feature for number of days 😇

**Pull request merged**
