### PR TITLE
Tech debt

### LINKED ISSUE #7: Tech debt: replace custom implementation with release deployment package
The .NET version sweeper is currently using custom HTTP and embedded JSON resources to read, parse, and cache representations of historical release data. While it is using the same data points that the unreleased `Microsoft.Deployment.DotNet.Releases` package - we should port over to using it once it is released.

See: https://github.com/dotnet/deployment-tools/pull/75

### PR DESCRIPTION
**Pull request by IEvangelist**
Remove custom HTTP calls that rely on _releases.json_, and manually parsing the JSON responses:

- Use the preview `Microsoft.Deployment.DotNet.Releases` package
- Delete unused files
- Fix unit tests

Fixes #7

### CODE REVIEW

**Comment by BillWagner** [comment]
Hmm. I'll review the code changes, but it looks like there is an issue with your .gitignore. There are a number of files that I don't think you want to add to the repo in this PR.

**Comment by BillWagner** [comment]
Reading the diffs, the changes look great. Let me know if you want me to look again after cleaning the PR files.

**Comment by IEvangelist** [comment]
Yeah, for this to be containerized we have to build out the .dll/.exe files and I put them in the /dist directory. This is intentional.

**Review by BillWagner — APPROVED** [review]
Thanks for the clarification. This LGTM to me.

**Comment by IEvangelist** [comment]
Hey @BillWagner - I created another issue to track the effort of removing the dlls and exes, and instead build the container from source. See, https://github.com/dotnet/versionsweeper/issues/18

**Pull request merged**
